### ISSUE TITLE
More Provider Options

### ISSUE THREAD

**Issue by alecmerdler** [vsternbach/angular-ts-decorators#1]
First of all, thank you so much for this very useful library. I am using it to ease the transition to Angular 2, and it is great to use Angular 2 syntax with AngularJS.

It would be great to add Angular 2's provider options into the NgModule's providers property. Specifically, the `useClass`, `useValue`, and `useFactory` options. This would be extremely useful to port over existing AngularJS factories and constants.
`{provide: SomeClassOrString, useFactory: () => new Implementation()}`

I would be willing to make a pull request with my attempt at the implementation, if you have any thoughts or insights, please let me know.

**Comment by vsternbach** [comment]
Hi, thanks for the feedback, glad to hear it's been useful for others as well :)
I am not really familiar with it, but will have a look on this, PRs are welcome
