### ISSUE TITLE
@Directive @Input('<') setter called before constructor

### ISSUE THREAD

**Issue by kylekatarnls** [vsternbach/angular-ts-decorators#102]
Hello,

I created a directive and noticed that `@Input` setter was called before the class to be constructed.

This prevents to use injected dependencies in those setters.

```ts
import {Directive, Input} from 'angular-ts-decorators';

@Directive({
    selector: 'foo-disabled',
})
export class FooDisabledDirective {
    @Input('<') public set fooDisabled(disabled: boolean) {
        console.log('fooDisabled', this.$element);
    }

    constructor(private $element: ng.IAugmentedJQuery) {
        console.log('construct', $element);
    }
}
```

```html
<div foo-disabled="5 == 5"></div>
```

Observed in console:
```
fooDisabled, undefined
construct, <div foo-disabled="5 == 5"></div>
```

Expected:
```
construct, <div foo-disabled="5 == 5"></div>
fooDisabled, <div foo-disabled="5 == 5"></div>
```

Expected order is the one we get in Angular 2+.

In my opinion, this is a bug. I'm not sure to be able to fix it but I can try to make a pull-request if you're agree to fix it.

Thanks.

**Comment by vsternbach** [comment]
You shouldn't be accessing $element in constructor according to angular, it should be done on ngOnInit hook

**Comment by kylekatarnls** [comment]
$element is not the problem, it would be the same with a service it won't be defined in the setter because the setter is called before the constructor. This is a non-sense. The constructor of a class should be called before any other method. because if the instance does not yet exists, I should be able to call any method.

Replace `$element` with `$filter` in the example above, and you'll get the same inconsistency: `this.$filter` is undefined because the setter is called before the constructor.

**Comment by vsternbach** [comment]
I see, what angularjs version are you using? There's an issue documented
here https://github.com/angular/angular.js/issues/14206

**Comment by kylekatarnls** [comment]
I'm in the worst case (1.5.11):
> In 1.5.10+, the default behavior will be to assign before calling the constructor, but you can change it to delay until before $onInit.

Indeed we should upgrade.

Thanks!

**Comment by kylekatarnls** [comment]
Thanks again for your quick response. We really love your library. ❤️
