### ISSUE TITLE
No Documentation On Injecting Angular Services

### ISSUE THREAD

**Issue by djbreen7** [vsternbach/angular-ts-decorators#104]
For example, I want to use `$timeout`. Previously, it would be injected as follows:

```javascript
MyController.$inject = ['$timeout'];
class MyComponent {
  constructor($timeout) {
    this.$timeout = $timeout;
  }
}
```

From what I'm reading in the documentation, it would be something like

```typescript
@Component({
    selector: 'my-component',
    templateUrl: './my.component.html',
    styles: ['./my.component.scss']
})
export class MyComponent {
    public useTimeout(): void {
        // How do we call $timeout?
       this.$timeout(() => console.log('hello'), 1000);
    }
};

@NgModule({
    declarations: [MyComponent],
    providers: [
        {
            provide: '$timeout', 
            // what goes here? 
        }
    ]
})
export class MyModule{
  static config($compileProvider: ng.ICompileProvider) {
    'ngInject';
    $compileProvider.debugInfoEnabled(false);
  }

  static run(/* what goes here? */ ) {
    'ngInject';
    // what goes here?
  } 
}

**Comment by vsternbach** [comment]
Cause it's injected the same way as before, look here for example:
https://github.com/vsternbach/angularjs-typescript-webpack/blob/master/src/app/hero-detail/hero-detail.component.ts

**Comment by djbreen7** [comment]
Thanks for clearing that up. I misunderstood the following piece of documentation to mean that I "can't define a constructor" for my components and thus can't use DI with a constructor.

> Please notice, that **you can't define constructor** and $inject anything into it, instead you need to specify all of the injections you want to provide for your module config and run blocks using 'ngInject' comment inside those static methods respectively.
