### ISSUE TITLE
providers with $get method

### ISSUE THREAD

**Issue by ryzhov** [vsternbach/angular-ts-decorators#123]
Hello,
Do you test providers with $get method that can be configured in config() call of module ?
I have issue with such provider, when I inject it in static config of ngModule class it have been striped of any properties and methods,
this is [ demo application ](https://github.com/ryzhov/menu-app/blob/fd94025970e14a2163edbbb852e536d48fbb40b4/src/index.ts#L20)
fell free to commit any suggestion fixes etc.

Thanks for project,
Aleksandr

**Comment by vsternbach** [comment]
Hey, providers are something that exists only in angularjs world and they can't be ported to angular 2+ applications as is, so there's no support for that in this library
