### ISSUE TITLE
component inheritance possible??

### ISSUE THREAD

**Issue by LalitAgrawala004** [vsternbach/angular-ts-decorators#14]
I am trying to achieve component inheritance ( something like [https://scotch.io/tutorials/component-inheritance-in-angular-2](https://scotch.io/tutorials/component-inheritance-in-angular-2))  using your decorator but it's not happening. could you pls let me know if it's possible?

**Comment by vsternbach** [comment]
It's possible, but right now it's not implemented, will check it out

**Comment by vsternbach** [comment]
@LalitAgrawala004 actually after doing some testing it turned out that component inheritance is supported out of the box, can you tell what exactly is not happening for you, please provide some example in plunker
