### ISSUE TITLE
Suppress warning messages

### ISSUE THREAD

**Issue by x87** [vsternbach/angular-ts-decorators#15]
When we do not provide an explicit NgModule/Injectable name the library throws a warning message telling "You are not providing explicit name be careful this code might not work as expected when minified". But if I'm 100% percent sure that the code will work (i.e. by disabling function names mangling in webpack), I would want not to see those messages polluting the console. 

Is it possible to introduce kind of a flag to suppress them? 
Thank you!

**Comment by vsternbach** [comment]
You are right, if you disable mangling in uglify it will work, but that's one of the reason to uglify in the first place - to compress variables names, anyway warning messages should be only in development mode, will add it in the future build

**Comment by x87** [comment]
Sorry again, but I don't see any minified file as of version 1.1.0. The library archive only contains `angular-ts-decorators.js` and `angular-ts-decorators.umd.js`. How it is supposed to work?

**Comment by vsternbach** [comment]
are you installing it with npm? there are angular-ts-decorators.min.js and angular-ts-decorators.umd.min.js as well, maybe your ide is collapsing them together with maps under unminified files, and of course you need to configure your bundler to take minified files in prod env, not sure if it's done automatically by webpack
<img width="351" alt="screen shot 2017-05-20 at 00 31 02" src="https://cloud.githubusercontent.com/assets/3830668/26267592/ba2d1fd0-3cf3-11e7-9f95-6c66a9cf15f8.png">

**Comment by x87** [comment]
Yeah, didn't notice Webstorm collapsed them, thank you, it works!
