### ISSUE TITLE
PipeTransform import

### ISSUE THREAD

**Issue by x87** [vsternbach/angular-ts-decorators#16]
After updating from v0.27 to 1.0.13 I've noticed that `PipeTransform` is no longer importable directly from 'angular-ts-decorators'. I.e. this code does not work:
```
import { Pipe, PipeTransform } from 'angular-ts-decorators';
...
export default class FooPipe implements PipeTransform {
```

A workaround would be:
```
import { Pipe } from 'angular-ts-decorators';
import { PipeTransform } from 'angular-ts-decorators/types/pipe';

export default class FooPipe implements PipeTransform {
```
Is it intentional?

Thank you!

**Comment by vsternbach** [comment]
Yeah, it's not exported directly and there's some kind of problem with interface export when bundling with rollup, trying to solve that issue.
On a side note, you don't actually need to write that some class implements PipeTransform it's more to comply with angular 2+ convention

**Comment by x87** [comment]
Strict following the Angular2 syntax is the reason I chose this library. My goal is to migrate the existing Angular 1.5 codebase to Angular2+ smoothly by rewriting code in TypeScript and decorating it as if I use Angular under the hood.
