### ISSUE TITLE
TypeScript 2.4 weak type errors

### ISSUE THREAD

**Issue by kfeinUI** [vsternbach/angular-ts-decorators#23]
Upgrading to TypeScript 2.4 yields a lot of errors from angular-ts-decorators due to its breaking change of adding greater weak type checking against interfaces. Nice minor version add, right? 

Since the decorators reference interfaces with all optional members, it will fail if none are provided. The workaround is to provide a dummy implementation in all of these places. Better solution would be to fix it here, if possible. Perhaps with more piecemeal interfaces such as in Angular. Thoughts?

**Comment by vsternbach** [comment]
Is typescript 2.4 officially out already? yesterday was still 2.3) anyhow I'll update to 2.4 to check the issues

**Comment by kfeinUI** [comment]
Yep. It's out. I had just seen the RC blog post and then they cut the release quite quickly. Got pulled into my build, so I had to go back and peg it at 2.3 for the time being.

**Comment by kfeinUI** [comment]
The issue is with the NgModule interface, which has only optional members. TypeScript 2.4 won't match against it when you don't implement any of them, which is the case for many of my modules which have an empty class body.

>  ERROR in [at-loader] Table.Module.ts:4:2
> TS2559: Type 'typeof TableHeaderModule' has no properties in common with type 'NgModule'.
> webpack: Failed to compile.
>

**Comment by vsternbach** [comment]
It seems that it is still unreleased, and I guess there's a reason for that, maybe there were too many problems when they released it, anyhow let's wait till it's officially released. I installed it explicitly in one of the projects and getting lots of errors also, trying to align types similar to angular interfaces

**Comment by kfeinUI** [comment]
Mine were only down to the weak interface issues. Only a few of ours
outside of the NgModule. The motivation for it makes sense, but doesn't
seem terribly appropriate for a minor release. They didn't mention a flag
for it, but I also haven't dug into that.

**Comment by vsternbach** [comment]
I had similar issue with @Directive, so added index signature there also, I'll try updating to 2.4.1 my other projects to see if there are any additional issues. It seems I'll be changing most of the interfaces to any, as they basically do in angular 2 decorators..
