### ISSUE TITLE
Add style/styleUrls to @Component decorator

### ISSUE THREAD

**Issue by nazar-kuzo** [vsternbach/angular-ts-decorators#25]
@vsternbach, Thanks a lot for your work.

Is it possible to add to @Component decorator 'style/styleUrls' properties to load template in the same way as it already is with 'templateUrl'?

**Comment by vsternbach** [comment]
Hello
I guess you mean load stylesheet and not template
There's no support in angularjs for loading styles the way templates are loaded, but maybe I can add support for styles property in the @Component decorator, where you could require your component's stylesheet using webpack for example, like shown here: https://angular.io/guide/component-styles#style-urls-in-metadata

**Comment by nazar-kuzo** [comment]
Yes, that's is exactly what I would like to see.

The reason I raised this question is to align angularjs components as much as possible to angular components, even if it is not supported by angularjs framework.

Appreciate your work!

**Comment by Swiftwork** [comment]
I noticed this was closed and while I am happy to implement the adding of the styles to the DOM myself, I am unsure how I would access these from the component metadata. Should I extend the component decorator to do this? What other suggestions do you have?

```typescript
@Component({
  selector: 'cNumber',
  styles: [require('./number.component.css')],
})
export class NumberComponent {

  @Input() in: Number;

  constructor() {}

  ngOnInit() {}
}
```

**Comment by nazar-kuzo** [comment]
@Swiftwork,

To make that working you need to use webpack css loader
