### ISSUE TITLE
Component hooks not mapped

### ISSUE THREAD

**Issue by kfeinUI** [vsternbach/angular-ts-decorators#26]
We found that the component hooks aren't being mapped due to the Object.keys() strategy. Upon inspection, it doesn't return any keys. This is from a TypeScript class.

Probably don't need to go that crazy with it. Loop through the hooks. If defined on the prototype, then map.

**Comment by vsternbach** [comment]
I'm sorry, I don't understand what exactly is the problem you are having with hooks. For me the hooks are working perfectly fine, can you give some example?

**Comment by kfeinUI** [comment]
Will submit a PR tomorrow once I'm in the office.

My understanding of Object.keys() is that it only covers enumerable
properties, which doesn't work for classes. My coworker and I were
experimenting in the console with this.


On Jun 25, 2017 2:55 PM, "Vlad Sternbach" <notifications@github.com> wrote:

I'm sorry, I don't understand what exactly is the problem you are having
with hooks. For me the hooks are working perfectly fine, can you give some
example?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vsternbach/angular-ts-decorators/issues/26#issuecomment-310920949>,
or mute the thread

**Comment by kfeinUI** [comment]
Yeah. ES6 modules. It's a webpack 2 + Babel  + TS build.
