### ISSUE TITLE
Support for {strictDi: true}

### ISSUE THREAD

**Issue by eric-simonton-sama** [vsternbach/angular-ts-decorators#29]
I'm trying out this tool today, and so far I really like it! I got my first component running, but I found I had to manually add hints for dependency injection to let it run with `strictDi` (and therefore with minified code), like this:

```ts
@Component({...})
export class MyComponent {
  public static $inject = ["$myDepdency"]; // <- I had to add this line
  constructor($myDependency) {...}
}
```

Is there some configuration I'm missing, or is this expected? If it is expected, that would be a great feature to support that automatically - if that's even possible.

Thanks!

**Comment by vsternbach** [comment]
Usually when working with angularjs one uses plugin like ngAnnotate, to add explicit annotations, but anyway I will add it for component

**Comment by eric-simonton-sama** [comment]
I was using `ngAnnotate`, which was working before I moved to the `@Component()` decorator. Does it work for you?

Anyway, it's not a well supported tool anymore anyway. E.g. it doesn't work if you set typescript to emit `es6` format modules instead of `commonJs` (which would be required for tree shaking in Webpack). The author has said he will not improve `ngAnnotate` because he found it to be a very slippery and error-prone slope to support more & more things with that tool.

So, thank you!  I think this is the right approach, and I'm glad you're willing to add it.  I look forward to the update.

**Comment by eric-simonton-sama** [comment]
Whoa - you had already released it! Thanks! 🎉

**Comment by vsternbach** [comment]
Yep, it works this way, you just need to add /*@ngInject*/ before component class constructor.
And you are right it's not working with es6 straight away, but there's a patch for it, you need to install ng-annotate-patched in addition to ng-annotate-loader and define the rule in webpack.config like this:
```
test: /\.ts$/,
exclude: /node_modules/,
use: [
 { loader: 'ng-annotate-loader', options: {  ngAnnotate: 'ng-annotate-patched' } },
 'awesome-typescript-loader'
 ]
```
