### ISSUE TITLE
Strange behavior when using pipes with Dependency Injection

### ISSUE THREAD

**Issue by vadim82** [vsternbach/angular-ts-decorators#3]
I have the following pipe
```
@Pipe({ name: "sanitize" })
export class SanitizePipe implements PipeTransform {
    /*@ngInject*/
    constructor(private $sanitize: ng.sanitize.ISanitizeService) { }
    public transform(input: string) {
        return this.$sanitize(input);
    }
}
```

When I try using this in my code, I keep getting errors like this `typeError: this.$sanitize is not a function`.
When I try to inspect the code for some reason $sanitize is an array instead of a function. 

Am I doing something wrong?

**Comment by vsternbach** [comment]
@vadim82 I think it has something to do with /*@ngInject*/ comment, cause decorator is doing it by itself, try removing it and tell me if it's the case, I'll try to think of the solution to this problem

**Comment by vadim82** [comment]
Doesn't seem to be. When I remove the comment, I get the same issue.

**Comment by vsternbach** [comment]
I've investigated the issue and it's a bug in Pipe registration method when injecting services from different modules, trying to solve, for now you can fallback to regular angular filter registration

**Comment by vadim82** [comment]
Great. Thank you for your help.
