### ISSUE TITLE
@Directive: NG2+ lifecycle hooks are not supported yet, while they are supported in @Component

### ISSUE THREAD

**Issue by christophercr** [vsternbach/angular-ts-decorators#32]
Hi again,

Another issue I found in the @Directive is the fact that the lifecycle hooks should still be defined using the NG1 syntax. The reason is that the call to [replaceLifecycleHooks](https://github.com/vsternbach/angular-ts-decorators/blob/master/src/component.ts#L34) similar to the one done in the @Component is missing.

Except for the ngAfterViewInit which is a component-only hook: https://angular.io/guide/lifecycle-hooks.

**Comment by vsternbach** [comment]
fixed in [2eef743](https://github.com/vsternbach/angular-ts-decorators/commit/2eef74329294e9f29ff9c4b85a913baa3c160e4c)
