### ISSUE TITLE
Component routeConfig

### ISSUE THREAD

**Issue by ronyf** [vsternbach/angular-ts-decorators#37]
Is there a way to access `$routeConfig` using the `@Component` decorator?

	.component('app', {
	  template:
		'<nav>\n' +
		'  <a ng-link="[\'CrisisCenter\']">Crisis Center</a>\n' +
		'  <a ng-link="[\'Heroes\']">Heroes</a>\n' +
		'</nav>\n' +
		'<ng-outlet></ng-outlet>\n',
	  $routeConfig: [
		{path: '/crisis-center/...', name: 'CrisisCenter', component: 'crisisCenter', useAsDefault: true},
		{path: '/heroes/...', name: 'Heroes', component: 'heroes' }
	  ]
	});

**Comment by vsternbach** [comment]
Are you using deprecated component router?

**Comment by ronyf** [comment]
ah.. crap
