### ISSUE TITLE
@Injectable: remove name param to align to Angular2+ and log an error instead

### ISSUE THREAD

**Issue by christophercr** [vsternbach/angular-ts-decorators#39]
Currently, the @Injectable has an optional "name" parameter, which at the end will be the name to be used while registering the service in Angular. However this name is only used in case you register the provider using the class:

```javascript
@NgModule({
  ...
  providers: [
   MyServiceClass
  ]
})
```

In that specific case, of course the Injectable "name" parameter is needed. In case you use the provider object syntax, it is not needed:

```javascript
@NgModule({
  ...
  providers: [
   { provide: "myServiceName", useClass/Factory/Value: MyServiceClass }
  ]
})
```

But if you don't provide the "name" param in the @Injectable you will still get the warning because the library assumes you "might" not be registering the service correctly.

I think that instead of logging a warning (which might pack your console with them if you have lots of services) the metadata for the service class should only be set if the name parameter is passed; then the registerProviders() function should log an error (or even throw) in case the provider is registered with the class and there is no name defined in the metadata.

In this way the @Injectable decorator will align to the Angular2+ decorator and you will know when your are "certainly" doing things wrong when you get the error in the console.

What do you think? Is it reasonable to do this?

**Comment by vsternbach** [comment]
Hello, good point, seems reasonable, I'll add this check.
Btw, you are getting warning only in development build, in production build all warnings are omitted

**Comment by voodoorider** [comment]
After upgrading to 3.7.7 from 1.x.x I am now getting a ton of errors similar to this:

```
SomeService was not registered as angular service:
        Provide explicit name in @Injectable when using class syntax or register it using object provider syntax:
        { provide: 'SomeService ', useClass: SomeService }
```

Is that intended? In Angular 2+ it is quite common to have an empty `@Injectable()` that is wired in the module using class:

```
@NgModule({
  id: 'SomeModule',
  providers: [
    SomeService
  ]
})
```

**Comment by FRSgit** [comment]
Also run into this issue
