### ISSUE TITLE
UglifyJSPlugin without source content

### ISSUE THREAD

**Issue by 8cells** [vsternbach/angular-ts-decorators#40]
angular-ts-decorators doesn`t work with webpack configuration:
```
    devtool: 'nosources-source-map',
    plugins: [
      new UglifyJSPlugin(),
    ]
```

How to fix this without changing configuration?

**Comment by vsternbach** [comment]
What exactly is not working, why should it matter if you are including sourcemaps in your build?

**Comment by 8cells** [comment]
Everything indicates that the module (with @NgModule) is not registered in the angular with UglifyJSPlugin
`Module 'XYZ' is not available! You either misspelled the module name or forgot to load it.`

I've checked a few times and it's because UglifyJSPlugin, not sourcemap

**Comment by 8cells** [comment]
Maybe in the wrong way I import this module.
How can I get the name (string) from @NgModule? I`m importing this module in old javascript angular code.

**Comment by 8cells** [comment]
Yes, I think problem is with import .ts module with @NgModule into .js old angular code

**Comment by 8cells** [comment]
I had some errors in the code, now it works
