### ISSUE TITLE
Is it possible to remove console.warn?

### ISSUE THREAD

**Issue by dwadezp** [vsternbach/angular-ts-decorators#48]
Hello,

is it possible to remove console.warn from this library? In some cases, when migrating legacy project to TS with angular-ts-decorators we need to have restrict='E' and link function and it's very annoying to see every time warnings. 

We know that using restrict='E' for directives is wrong but we really need it and we will be very happy i you allow to remove warnings. I've created pull request https://github.com/vsternbach/angular-ts-decorators/pull/47

Could you please take a look at it?

**Comment by vsternbach** [comment]
fixed in #47
