### ISSUE TITLE
No exported member 'IControllerConstructor'

### ISSUE THREAD

**Issue by FrozenDroid** [vsternbach/angular-ts-decorators#51]
Hi,

Thanks for this great package!
I'd love to use it, but I'm having a little bit of trouble with it.
I get this error:
```
 error  in /Users/vincent/Code/Docker/ecotrace/volumes/website/node_modules/angular-ts-decorators/types/component.d.ts

(8,102): error TS2694: Namespace '"/Users/vincent/Code/Docker/ecotrace/volumes/website/node_modules/@types/angular/index".angular' has no exported member 'IControllerConstructor'.
```
When including the package.

I'm using TypeScript 2.5.3 and AngularJS 1.6.6

**Comment by vsternbach** [comment]
Are you using somewhere IControllerConstructor? Can you please post a
sample of your code?

**Comment by FrozenDroid** [comment]
Nope, not using it anywhere. 
However, when I put `import { IControllerConstructor } from 'angular';` in `component.d.ts` and change line 10 accordingly, it works fine...

**Comment by vsternbach** [comment]
I guess there's something wrong with your setup then, cause ng.IControllerConstructor should be recognized as long as you have @types/angular installed, check if you have updated version of @types/angular and also can you share somehow the setup of your system or dummy project just with some component so we can pinpoint the problem

**Comment by FrozenDroid** [comment]
Thing is, I get this error just by `npm install`'ing this package... I do have `@types/angular` installed. Really not sure why importing `IControllerConstructor` fixes it but it does, for me.

**Comment by FrozenDroid** [comment]
Actually, changing `angular.IControllerConstructor` to `ng.IControllerConstructor` does the trick, too. I suspect `angular.` doesn't work properly because of [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular/index.d.ts#L12) line.  
Any ideas?

**Comment by vsternbach** [comment]
I am pretty sure there's no any problem with angularjs typings, I think it has to do something with your setup, cause nobody else isn't reporting this issue.
Can you post to jsfiddle a sample project with you setup, package.json, tsconfig, some dummy component, cause otherwise I don't know how to help you

**Comment by FrozenDroid** [comment]
My tsconfig.json: https://hastebin.com/ifiqizacud.json
My package.json: https://hastebin.com/onopilovof.json

Components don't matter because even if I don't use any components, I still get the same error (Which is very weird to me but alas)

**Comment by vsternbach** [comment]
I you just starting working with typescript? Usually you should exclude node_modules also in tsconfig

**Comment by FrozenDroid** [comment]
Mhm, I am quite new to TypeScript but definitely liking it so far.  
I tried excluding `node_modules`, but that doesn't help either.
When looking at the autocomplete results on `angular` or `ng` of my IDE (PHPStorm 2017.3), it only shows results of `IAngularStatic`... But `ng` does work.

Safe to say, I'm pretty confused :P

**Comment by vsternbach** [comment]
you should have "files" property in your tsconfig, where usually you'll have one (sometimes several if you have some unrelated modules) entry points of your application, right now typescript compiles all of your project ts and d.ts files. This is an excerpt from one of my tsconfigs:
```
  "files": [
    "web/my-custom-typings.d.ts",
    "web/index.ts"
  ]
```

**Comment by FrozenDroid** [comment]
Hmm... I'll have to figure out how to do this with https://github.com/JeffreyWay/laravel-mix/pull/812

**Comment by FrozenDroid** [comment]
Hmm, no, that doesn't help either. I added my app's entrypoint to "files" and that didn't do it.

**Comment by FrozenDroid** [comment]
@vsternbach Is this package confirmed to work with TypeScript 2.5.3?

**Comment by vsternbach** [comment]
It was working for me since 2.1 I think, now project is on 2.6.1

**Comment by vsternbach** [comment]
btw, are you sure that PHPStorm fully supports frontend development tools integration?

**Comment by FrozenDroid** [comment]
Yep. Absolutely everything works except this tiny issue. Besides, I'm not using PHPStorm to compile my code, I'm using webpack (laravel-mix)

**Comment by vsternbach** [comment]
Ah, I see, so you not compiling it directly but through some wrapper if I
understand correctly, try compiling it directly with tsc

**Comment by FrozenDroid** [comment]
Sorry, it took me a while to follow up on this. I tried compiling directly through tsc using my tsconfig.json and it still gives me the same error.

**Comment by FrozenDroid** [comment]
Oh, this is fairly interesting. In the source `component.ts`, `ng.IControllerConstructor` is used but the type replaces that with `angular.IControllerConstructor`. Is that even intended?

**Comment by vsternbach** [comment]
Hello, you can try upgrade to version 3.0 and check if it solves your issue

**Comment by FrozenDroid** [comment]
That fixed it. Cheers!
