### ISSUE TITLE
Partial decoration

### ISSUE THREAD

**Issue by pdashford** [vsternbach/angular-ts-decorators#53]
Is it possible to use partial decoration. So as an example we would use the new decorators for our service, then the components, then the modules. However when I tried this it wanted everything to be decorated together. Look forward to your thoughts.

**Comment by vsternbach** [comment]
Hi, it's possible to gradually decorate you codebase, but NgModule class is still needed, for example, if you have code like this:
```
export const appModule = angular
  .module('AppModule', [
  'ui.router',
  'ui.bootstrap',
  ])
  .service('someService', SomeService)
  .config(appPreConfigAppIq)
  .run(appPostConfig);
```
and let's say you've decorated SomeService, the you can register it like this and leave undecorated declarations as is:
```
@NgModule({
  id: 'AppModule',
  imports: [
  'ui.router',
  'ui.bootstrap',
  ],
  providers: [
    { provide: 'SomeService', useClass: SomeService },
  ]
})
export class AppModule {}
(AppModule as NgModule).module
  .config(appPreConfigAppIq)
  .run(appPostConfig);
```
