### ISSUE TITLE
Extending a component with HostListener and using $element

### ISSUE THREAD

**Issue by mebibou** [vsternbach/angular-ts-decorators#58]
From the source I can see that when we use `@HostListener` on a component, the controller will automatically inject `$element`, but if we also want to use `$element` in the controller then we cannot simply use the `$element` since it is set as private already. I think either the `$element` should be set as `protected`/`public` or should only be added if not already present

**Comment by vsternbach** [comment]
Even if it would be public/protected you won't be able to access, cause it's injected in the extending class at runtime, so in typescript you'll get compilation error when trying to access it, but there's no problem to inject $element in component/directive that uses HostListener, it will be just injected twice in the end

**Comment by davestreet26** [comment]
Read it regular

**Comment by vsternbach** [comment]
What!?
