### ISSUE TITLE
Default value of property when using @Input

### ISSUE THREAD

**Issue by mebibou** [vsternbach/angular-ts-decorators#60]
Normally when using Angular this code will set the Input with a default value:
```
@Component{}
export class Component implements AfterViewInit {
  @Input()
  value = 1;

  ngAfterViewInit() {
    console.log(this.value); // = 1
  }
}
```
But it does not work with angular-ts-decorators, I always have `undefined` as a value and need to do the default value in `ngAfterViewInit`. Could it work the same way?

**Comment by erhardos** [comment]
Today I accidentally done this:
`@Input('<?') options: { redirectTo: string } = { redirectTo: '/settings' };`

The key part is setting input parameter as optional.
Cheers!

**Comment by vsternbach** [comment]
Maybe I should add `?` by default to all inputs, not sure what the implications could be though

**Comment by mebibou** [comment]
@vsternbach well I guess since `Input` are all optional by default, I don't see how it could hurt
