### ISSUE TITLE
@Inject doesn't always work.

### ISSUE THREAD

**Issue by 8cells** [vsternbach/angular-ts-decorators#64]
It doesn`t always work.

I don't know why, it's possible that by building on many threads, but it doesn't always work for me (If I have many imports)

With the following code everything works fine:
```javascript
function Inject(name) {
    return function (target, propertyKey, parameterIndex) {
        if (target.$inject) {
            target.$inject[parameterIndex] = name;
        }
        else {
            console.error("Annotations should be provided as static $inject property in order to use @Inject decorator");
        }
    };
}
````

Plese merge it.

**Comment by vsternbach** [comment]
Hmm, strange, but your solution seems more efficient anyway, didn't know why I've used splice instead  of just re-assigning, thanks

**Comment by mebibou** [comment]
I don't know if it is related, but this also doesn't work:
```
export class MyModule {
  /*@ngInject*/
  static run(
    @Inject('My.Service') Service
  ) {
    Service.init();
  }
}
```
it will throw `Uncaught Error: [$injector:unpr] Unknown provider: ServiceProvider <- Service`

**Comment by vsternbach** [comment]
For static methods, there should be `'ngInject';` comment inside the method and not before as in constructor, I'll update the documentation

**Comment by mebibou** [comment]
@vsternbach I've tried like this with same error:
```
@Injectable('My.Service')
export class Service {
  public init() {}
}

@NgModule({
  providers: [
    Service
  ]
})
export class MyModule {
  static run(
    @Inject('My.Service') Service
  ) {
    'ngInject';
    Service.init();
  }
}
```

**Comment by vsternbach** [comment]
it's a bug, opened a new issue for it #65

**Comment by mebibou** [comment]
great, the tests are passing now with `3.7.3`, thanks

**Comment by meldridon** [comment]
Am I missing something? When I do this I get "Annotations should be provided as static $inject property in order to use @Inject decorator".

```
@NgModule({
    id: "MyModule",
})
export class Module {
    static config(
        @Inject("$locationProvider") test: ng.ILocationProvider
    ) {
        'ngInject';
        test.html5Mode(true);
    }
}
```

Using 3.7.5 and TypeScript 2.8.x
