### ISSUE TITLE
ViewChild by id not working since 3.7.x

### ISSUE THREAD

**Issue by mebibou** [vsternbach/angular-ts-decorators#66]
I was using `3.6.1` in my component with `ViewChild()` and it was working fine. I just tried to update to `3.7.3` but now the references to the views point to the DOM elements themselves, i.e
```
export class ParentComponent {
  @ViewChild('#viewId')
  child: ChildComponent;
}
```

`parentComponent.child` does not point to the controller anymore but the DOM element itself.

I guess this is due to https://github.com/vsternbach/angular-ts-decorators/compare/v3.7.1...v3.7.2#diff-7db1d7c8dc88ce00d1aa236fa0c128cc, so it means support of children by selector is no longer supported? I havent seen it not being supported by angular

**Comment by vsternbach** [comment]
It's supported, but it should be component's selector, and not some other html attribute.
Besides why do you provide selector and not component's class in decorator, is there any rational behind it?
you can just write: @ViewChild(ChildComponent) child: ChildComponent;

**Comment by mebibou** [comment]
because if I have 2 and I want to have a pointer to each?
```
<child id="foo"></child>
<child id="bar"></child>

@ViewChild('#foo')
fooChild: ChildComponent;

@ViewChild('#bar')
barChild: ChildComponent;
```
what's the alternative?

**Comment by vsternbach** [comment]
You're kind of using it wrong, from angular's ViewChild documentation:
>selector - the directive type or the name used for querying.
By the name used for querying they are basically referring to template reference that doesn't exist in angularjs.
Actually I've just realized that querying by component's selector isn't available in angular, only type or template reference.
So I guess, we can think maybe how to implement this template reference in angularjs in a more elegant manner, rather than re-using id attribute

**Comment by vsternbach** [comment]
Actually, maybe it's a good idea to remove support for querying by selector and replace it with quering by id, or maybe use something like this: https://medium.com/@alireza.mirian/mimicking-angular-template-references-in-angularjs-with-a-10-line-directive-c0687a3ddaa6

**Comment by mebibou** [comment]
hum I'm not sure adding a special attribute to query for is a good idea, we should stick as close as possible to the angular way
What about when doing `@ViewChild('my-selector')` it automatically does a query of `.querySelector('#my-selector')`? you'd still have to change the templates if you switch to angular but at least you won't change the js code

**Comment by vsternbach** [comment]
I tend to agree with you, will go for now with id attribute as analog for template reference, will submit a fix soon
