### ISSUE TITLE
Support for module.provider(...)

### ISSUE THREAD

**Issue by alirezamirian** [vsternbach/angular-ts-decorators#67]
Currently there seem to be no way to add service providers registered with `.provider(...)` api of angular modules, to modules registered with `@ngModule`.

BTW, thanks for your nice job.

**Comment by vsternbach** [comment]
Since there's no such thing as provider in angular, I've decided to remove support for it, cause you'll need to refactor it anyway when porting to angular, but you can still access angularjs module and register it the regular way:
```
@NgModule({
  declarations: [
    AppComponent
  ]
})
export class AppModule {}
(AppModule as NgModule).module.provider(...)
```

**Comment by alirezamirian** [comment]
I see. I didn't know about `module` property that `NgModule` adds.
Previously I was writing `angular.module('moduleId')` to get a hold of my
module and use `provider` api.
