### ISSUE TITLE
Examples use "templateUrl" instead of "template"

### ISSUE THREAD

**Issue by JackD111** [vsternbach/angular-ts-decorators#68]
Hi,

there is a small error in the examples. They should use the "template" property of the component options instead of the incorrect "tempalteUrl" property.

Wrong:
```
...
const templateUrl = require('./todo-form.html');

@Component({
  selector: 'todoForm',
  templateUrl
})
...
```

Right:
```
...
const template = require('./todo-form.html');

@Component({
  selector: 'todoForm',
  template
})
...
```

**Comment by vsternbach** [comment]
it depends on weback config, if you have ngTemplate loader, then it is as in example, otherwise it should be template
