### ISSUE TITLE
Need help on using @Component 

### ISSUE THREAD

**Issue by LalitAgrawala004** [vsternbach/angular-ts-decorators#7]
Hi
I am trying to use @Component decorators but it's not working for me. My application is written in AngularJs1.6. recently, I tried implement typescript and angular-ts-decorators for one of existing component. As mentioned in readme, 
I created employeeStatusComponent.ts as 

```
import { Component, Input, Output } from 'angular-ts-decorators';
@Component({
  selector: 'employee-status',
  templateUrl: '/partials/employee/employee-status.html'
})
export default class EmployeeStatusComponent{<<logic here>>}
```

created a employeeStatusModule.ts as

```
import { NgModule } from 'angular-ts-decorators';
import EmployeeStatusComponent from './employeeComponent';

@NgModule({
  declarations: [EmployeeStatusComponent]
})
export default class EmployeeStatusModule{}
```
I injected the above module to another module where employeeStatusComponent was used as component previously in angularJS1.6 javascript style. ( it was used like EmployeePayrollComponent)

```
import EmployeeStatusModule from './employeeStatusModule';
import EmployeePayrollComponent from './employeePayrollComponent';
import EmployeeController from './employeeController';

export default angular.module( 'Portal.Employee', [
EmployeeStatusModule
])
.config(StateConfig)
.controller(EmployeeController.name, EmployeeController)
.component(EmployeePayrollComponent.name, EmployeePayrollComponent)
```
and lastly, I used `<employee-status></employee-status>` (component selector) in my **employee.html** page. when I am running the application the employee-status component not showing any output. looks like it's not even getting executed.
I also did `npm install --save-dev @types/angular` and my webpack build is running fine ( no errors)

Could you pls check and let me know if I am missing anything? 
Thanks a lot in advance.

**Comment by vsternbach** [comment]
Hi
When using @NgModule as dependency in other non-decorated module, you need to expose the angular module itself, not the decorated one, like this:
export default angular.module( 'Portal.Employee', [
EmployeeStatusModule.module
])

**Comment by LalitAgrawala004** [comment]
@vsternbach i tried the way you mentioned. but getting error -> 
Error: [ng:areq] Argument 'module' is not a function, got Object

**Comment by kfeinUI** [comment]
It's that he was using kebab-case for the selector. Is there a reason it's not supported? Would be more consistent with Angular.

**Comment by LalitAgrawala004** [comment]
@vsternbach @kfeinUI also it should be 
```
export default angular.module( 'Portal.Employee', [
EmployeeStatusModule.module.name
])
```

**Comment by vsternbach** [comment]
Sorry, my bad, it should be EmployeeStatusModule.name, not module and yes the selector name should be camelcase as in angularjs, and you are right @kfeinUI, it's a good idea to add support for kebab case following angular 2 syntax
