### ISSUE TITLE
Inject components into the plain old `angular.module('app')`

### ISSUE THREAD

**Issue by CarterLi** [vsternbach/angular-ts-decorators#79]
Thanks for a great project! I'm trying to migrating my HUGE angular.js project to Angular2+.

The first problem I'm facing is that in my project, every components, directives and services are injected in their own file.

For example:

```js
import app from '@/the_angular_module_defination_file.js';
import templateHtml from './template.html';

class MyComponent {
}

app.component('myComponent', {
  bindings: {
    // ...
  },
  controller: MyComponent,
  template: templateHtml,
}
```

Now I'm refactoring this component. I can transform my component to the new Angular2+ syntax with decorators. But with the new component syntax, I must inject the component with the new `@NgModule` syntax, which forces I transform my every other component and directive to new syntax to work with.

I want to migrate my project step by step, which, in my opinion, is the goal of this project. So my problem is how can I migrate `MyComponent` without changing the definition of `angular.module('app', [])` so that other components can continually work with old syntax.

Thanks again!

**Comment by vsternbach** [comment]
I suggest that you turn your angular module definition file that you're importing into NgModule and export the class itself, you can always access the original angular.module from NgModule, see the appropriate section in readme file

**Comment by CarterLi** [comment]
Thanks for your reply.

Another question: How can I use ui-router with new syntax?

**Comment by vsternbach** [comment]
Look here for example https://github.com/vsternbach/angularjs-typescript-webpack/blob/master/src/app/app-routing.module.ts

**Comment by CarterLi** [comment]
OK, thanks
