### ISSUE TITLE
Getting angular.js:15536 Error: [$injector:unpr] Unknown provider: xProvider <- x 

### ISSUE THREAD

**Issue by Cyberdada** [vsternbach/angular-ts-decorators#83]
Hi, 
I'm not sure if I just misconfigured my application or if this is an actual error ....

I Have a service declared as : 

import { Injectable } from 'angular-ts-decorators'

@Injectable()
export class NavigationService { 
reorderNavigationItem(): any { return 'e';}

refreshNavigationItems(): any {
    return 'hekkopekko';
}
}

And in the module I have added it as a provider like this: 

providers: [
        { provide: 'NavigationService', useClass: NavigationService }
    ]

( Itried to to it in angular 2+ style, but I got an error then saying that I needed to give the @injectable an explicit name) 

In my component Im trying to inhect the service in the constructor like this 
constructor(private navigationService: NavigationService) 

Is there something else I need to do? 
I'm running angular 1.7.4 and webpack

The error is 
Error: [$injector:unpr] Unknown provider: navigationServiceProvider <- navigationService

I have no run or config part  in my module (tried to define navigationServiceProvider in the config part, but that did not work either. ) 

Best Regards

Magnus

**Comment by vsternbach** [comment]
If you're not using explicit annotations the name of the argument has to be the same as defined in provide property NavigationService
