### ISSUE TITLE
Registering a component example

### ISSUE THREAD

**Issue by ShinDarth** [vsternbach/angular-ts-decorators#9]
Hi, I'm trying to use angular-ts-decorators in my project:

https://github.com/ShinDarth/Othello

I've managed to convert one of my components using the ``@Component`` decorator. It compiles without errors but when I run the app in the browser, the component is not there and I get no errors in console.

This is the file where I'm including my components and services: https://github.com/ShinDarth/Othello/blob/master/app/index.ts

can you please give an example of how to register components/services using the decorators ?

**Comment by vsternbach** [comment]
Hi @ShinDarth, you need to register your module with @NgModule decorator, see an example in readme

**Comment by ShinDarth** [comment]
Yes I'm trying it:

https://github.com/ShinDarth/Othello/tree/angular-ts-decorators

but does not work. Can you give me a hint please?

Thanks for creating angular-ts-decorators!
