### ISSUE TITLE
Please provide example of using @Directive decorator

### ISSUE THREAD

**Issue by markoffk** [vsternbach/angular-ts-decorators#99]
It seems that @Directive annotation not working fully - link function not executing

Thanks!

**Comment by vsternbach** [comment]
don't understand what do you mean, there's no such decorator as @decorator

**Comment by markoffk** [comment]
@vsternbach Sorry very much. My mistake. I meant @Directive decorator which seems not working.
Can you provide any working examples with "link" function?

**Comment by vsternbach** [comment]
@directive supports only directives using controller syntax, have you looked into issue #42 there's an example there
In general you should avoid using link or compile in directive cause you won't be able to port them to angular, the whole point of this library is to make it easier to port angularjs codebase to newer angular

**Comment by markoffk** [comment]
@vsternbach thank you very much!
